/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#004e5c",
        "on-tertiary-fixed": "#2d1600",
        "primary-fixed": "#aaedff",
        "on-secondary-fixed": "#001f23",
        "secondary": "#006971",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#5cd7e5",
        "inverse-on-surface": "#f3f0ef",
        "surface-container-low": "#f6f3f2",
        "secondary-fixed": "#88f3ff",
        "on-primary-fixed": "#001f26",
        "tertiary-fixed-dim": "#ffb874",
        "on-secondary-fixed-variant": "#004f56",
        "on-surface": "#1c1b1b",
        "surface-container-high": "#eae7e7",
        "primary": "#006071",
        "on-tertiary-fixed-variant": "#6a3b00",
        "on-surface-variant": "#3e484b",
        "surface-bright": "#fcf9f8",
        "surface": "#fcf9f8",
        "outline-variant": "#bec8cc",
        "background": "#fcf9f8",
        "surface-container-highest": "#e5e2e1",
        "on-background": "#1c1b1b",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffdcbf",
        "inverse-primary": "#7ad3e9",
        "on-error-container": "#93000a",
        "tertiary": "#834a00",
        "on-secondary-container": "#006d76",
        "surface-variant": "#e5e2e1",
        "surface-dim": "#dcd9d9",
        "on-primary-container": "#e3f9ff",
        "on-secondary": "#ffffff",
        "inverse-surface": "#313030",
        "outline": "#6e797c",
        "secondary-container": "#79f1ff",
        "primary-container": "#007b8f",
        "on-error": "#ffffff",
        "surface-tint": "#006879",
        "tertiary-container": "#a55f00",
        "surface-container": "#f0eded",
        "error": "#ba1a1a",
        "on-tertiary-container": "#fff3eb",
        "primary-fixed-dim": "#7ad3e9"
      },
      borderRadius: {
        'none': '0',
        'sm': '4px',
        'DEFAULT': '6px',
        'md': '8px',
        'lg': '10px',
        'xl': '14px',
        'pill': '999px',
        'full': '9999px'
      },
      spacing: {
        'unit': '4px',
        'stack-lg': '20px',
        'stack-md': '12px',
        'container-padding': '16px',
        'gutter': '12px',
        'stack-sm': '6px',
        'safe': 'env(safe-area-inset-bottom, 16px)',
        'safe-top': 'env(safe-area-inset-top, 0px)',
        'safe-bottom': 'env(safe-area-inset-bottom, 16px)'
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        // 保持旧名称兼容性
        "label-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "price-tag": ["Inter", "sans-serif"]
      },
      fontSize: {
        'display-xxl': ['44px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-xl': ['32px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg': ['28px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-md': ['24px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-sm': ['18px', { lineHeight: '22px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['20px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-md': ['18px', { lineHeight: '22px', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '20px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '22px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '18px', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
      },
      boxShadow: {
        'm3-1': '0px 1px 2px rgba(0, 0, 0, 0.3), 0px 1px 3px 1px rgba(0, 0, 0, 0.15)',
        'm3-2': '0px 1px 2px rgba(0, 0, 0, 0.3), 0px 2px 6px 2px rgba(0, 0, 0, 0.15)',
        'm3-3': '0px 4px 8px 3px rgba(0, 0, 0, 0.15), 0px 1px 3px rgba(0, 0, 0, 0.3)',
        'm3-4': '0px 6px 10px 4px rgba(0, 0, 0, 0.15), 0px 2px 3px rgba(0, 0, 0, 0.3)',
        'm3-5': '0px 8px 12px 6px rgba(0, 0, 0, 0.15), 0px 4px 4px rgba(0, 0, 0, 0.3)',
      }
    },
  },
  plugins: [],
}
