/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#004e5c",
        "on-tertiary-fixed": "#2d1600",
        "primary-fixed": "#aaedff",
        "on-secondary-fixed": "#001f23",
        "secondary": "#006971",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#5cd7e5",
        "inverse-on-surface": "#f3f0ef",
        "surface-container-low": "#f6f3f2",
        "secondary-fixed": "#88f3ff",
        "on-primary-fixed": "#001f26",
        "tertiary-fixed-dim": "#ffb874",
        "on-secondary-fixed-variant": "#004f56",
        "on-surface": "#1c1b1b",
        "surface-container-high": "#eae7e7",
        "primary": "#006071",
        "on-tertiary-fixed-variant": "#6a3b00",
        "on-surface-variant": "#3e484b",
        "surface-bright": "#fcf9f8",
        "surface": "#fcf9f8",
        "outline-variant": "#bec8cc",
        "background": "#fcf9f8",
        "surface-container-highest": "#e5e2e1",
        "on-background": "#1c1b1b",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffdcbf",
        "inverse-primary": "#7ad3e9",
        "on-error-container": "#93000a",
        "tertiary": "#834a00",
        "on-secondary-container": "#006d76",
        "surface-variant": "#e5e2e1",
        "surface-dim": "#dcd9d9",
        "on-primary-container": "#e3f9ff",
        "on-secondary": "#ffffff",
        "inverse-surface": "#313030",
        "outline": "#6e797c",
        "secondary-container": "#79f1ff",
        "primary-container": "#007b8f",
        "on-error": "#ffffff",
        "surface-tint": "#006879",
        "tertiary-container": "#a55f00",
        "surface-container": "#f0eded",
        "error": "#ba1a1a",
        "on-tertiary-container": "#fff3eb",
        "primary-fixed-dim": "#7ad3e9"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "stack-lg": "24px",
        "stack-md": "16px",
        "container-padding": "16px",
        "gutter": "12px",
        "stack-sm": "8px",
        "safe": "env(safe-area-inset-bottom, 16px)",
        "safe-top": "env(safe-area-inset-top, 0px)",
        "safe-bottom": "env(safe-area-inset-bottom, 16px)"
      },
      fontFamily: {
        "label-lg": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "price-tag": ["Hanken Grotesk", "sans-serif"]
      },
      fontSize: {
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "price-tag": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
